In [1]:
import sqlite3 as sql
from pathlib import Path
import numpy as np

data_folder = Path("C:\\Users\\dan_b\\OneDrive\\Projekte\\kaggle-iris")
filepath = data_folder / "database.sqlite"
conn  = sql.connect(filepath)
cur = conn.cursor()
 

In [2]:
query = '''
SELECT Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species FROM iris'''
sth = cur.execute(query)
daten = np.empty((1,6))
results = sth.fetchall()
for Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species in results:
    
	print(Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species)

1 5.1 3.5 1.4 0.2 Iris-setosa
2 4.9 3 1.4 0.2 Iris-setosa
3 4.7 3.2 1.3 0.2 Iris-setosa
4 4.6 3.1 1.5 0.2 Iris-setosa
5 5 3.6 1.4 0.2 Iris-setosa
6 5.4 3.9 1.7 0.4 Iris-setosa
7 4.6 3.4 1.4 0.3 Iris-setosa
8 5 3.4 1.5 0.2 Iris-setosa
9 4.4 2.9 1.4 0.2 Iris-setosa
10 4.9 3.1 1.5 0.1 Iris-setosa
11 5.4 3.7 1.5 0.2 Iris-setosa
12 4.8 3.4 1.6 0.2 Iris-setosa
13 4.8 3 1.4 0.1 Iris-setosa
14 4.3 3 1.1 0.1 Iris-setosa
15 5.8 4 1.2 0.2 Iris-setosa
16 5.7 4.4 1.5 0.4 Iris-setosa
17 5.4 3.9 1.3 0.4 Iris-setosa
18 5.1 3.5 1.4 0.3 Iris-setosa
19 5.7 3.8 1.7 0.3 Iris-setosa
20 5.1 3.8 1.5 0.3 Iris-setosa
21 5.4 3.4 1.7 0.2 Iris-setosa
22 5.1 3.7 1.5 0.4 Iris-setosa
23 4.6 3.6 1 0.2 Iris-setosa
24 5.1 3.3 1.7 0.5 Iris-setosa
25 4.8 3.4 1.9 0.2 Iris-setosa
26 5 3 1.6 0.2 Iris-setosa
27 5 3.4 1.6 0.4 Iris-setosa
28 5.2 3.5 1.5 0.2 Iris-setosa
29 5.2 3.4 1.4 0.2 Iris-setosa
30 4.7 3.2 1.6 0.2 Iris-setosa
31 4.8 3.1 1.6 0.2 Iris-setosa
32 5.4 3.4 1.5 0.4 Iris-setosa
33 5.2 4.1 1.5 0.1 Iris-setosa
34 5.5

In [3]:
a=np.array(np.zeros((3,4)))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
query = '''
SELECT Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species FROM iris'''
sth = cur.execute(query)
daten = np.empty((1,6))
results = sth.fetchall()
for Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species in results:
    
	print(Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species)

1 5.1 3.5 1.4 0.2 Iris-setosa
2 4.9 3 1.4 0.2 Iris-setosa
3 4.7 3.2 1.3 0.2 Iris-setosa
4 4.6 3.1 1.5 0.2 Iris-setosa
5 5 3.6 1.4 0.2 Iris-setosa
6 5.4 3.9 1.7 0.4 Iris-setosa
7 4.6 3.4 1.4 0.3 Iris-setosa
8 5 3.4 1.5 0.2 Iris-setosa
9 4.4 2.9 1.4 0.2 Iris-setosa
10 4.9 3.1 1.5 0.1 Iris-setosa
11 5.4 3.7 1.5 0.2 Iris-setosa
12 4.8 3.4 1.6 0.2 Iris-setosa
13 4.8 3 1.4 0.1 Iris-setosa
14 4.3 3 1.1 0.1 Iris-setosa
15 5.8 4 1.2 0.2 Iris-setosa
16 5.7 4.4 1.5 0.4 Iris-setosa
17 5.4 3.9 1.3 0.4 Iris-setosa
18 5.1 3.5 1.4 0.3 Iris-setosa
19 5.7 3.8 1.7 0.3 Iris-setosa
20 5.1 3.8 1.5 0.3 Iris-setosa
21 5.4 3.4 1.7 0.2 Iris-setosa
22 5.1 3.7 1.5 0.4 Iris-setosa
23 4.6 3.6 1 0.2 Iris-setosa
24 5.1 3.3 1.7 0.5 Iris-setosa
25 4.8 3.4 1.9 0.2 Iris-setosa
26 5 3 1.6 0.2 Iris-setosa
27 5 3.4 1.6 0.4 Iris-setosa
28 5.2 3.5 1.5 0.2 Iris-setosa
29 5.2 3.4 1.4 0.2 Iris-setosa
30 4.7 3.2 1.6 0.2 Iris-setosa
31 4.8 3.1 1.6 0.2 Iris-setosa
32 5.4 3.4 1.5 0.4 Iris-setosa
33 5.2 4.1 1.5 0.1 Iris-setosa
34 5.5

In [5]:
b=np.array(np.random.random((3,4)))
print(b
     )

[[0.52110781 0.91901623 0.07107457 0.72749216]
 [0.27063131 0.89403931 0.52998603 0.90766415]
 [0.32901463 0.14289966 0.49668164 0.02922379]]


In [6]:
a+b

array([[0.52110781, 0.91901623, 0.07107457, 0.72749216],
       [0.27063131, 0.89403931, 0.52998603, 0.90766415],
       [0.32901463, 0.14289966, 0.49668164, 0.02922379]])

In [7]:
a=a*np.random.random((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
a.size

12

In [9]:
a.shape

(3, 4)

In [10]:
a.dtype

dtype('float64')

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a.ndim

2

In [13]:
c=np.array(np.arange(12).reshape((3,4)))
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
c[:,2]

array([ 2,  6, 10])

In [15]:
c[2,:]

array([ 8,  9, 10, 11])

In [16]:
print(np.random.permutation(c))

[[ 0  1  2  3]
 [ 8  9 10 11]
 [ 4  5  6  7]]


In [17]:
for i in range(1,10):
    print(np.random.permutation(c))

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]
[[ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]
[[ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
for i in range(1,10):
    print(np.random.permutation(np.ravel(c)))

[ 0  9  8  2  4  5  1  6  3 10  7 11]
[11  9  3  4  1 10  6  5  0  2  7  8]
[ 0  9  5  1  8 10  7  6  4  3 11  2]
[ 9  6  7  8  3  2 10  5  4  1  0 11]
[ 5  7  0  3  9 11  1 10  2  6  4  8]
[ 4 11  2  1 10  9  5  6  8  7  0  3]
[ 0  2  7  9 10 11  1  5  6  3  4  8]
[10  0  3  5  1  8  4  9  2  6  7 11]
[ 2 10  1  7  0 11  6  5  4  3  8  9]


In [19]:
for i in range(1,10):
    print(np.random.permutation(np.ravel(c)).reshape(3,4))

[[ 9  8  2  6]
 [ 1  7 11  0]
 [ 5  4 10  3]]
[[ 7 10  8  5]
 [ 0  9  3  1]
 [ 4 11  6  2]]
[[11  5  8  9]
 [ 0  2  6  4]
 [ 7  1  3 10]]
[[ 7 10  3  9]
 [ 2  4  1  5]
 [ 8  6 11  0]]
[[ 1  6  4 11]
 [ 8 10  3  2]
 [ 9  5  0  7]]
[[ 5  9  2  4]
 [ 7  6  3 11]
 [ 1  0  8 10]]
[[ 2  0  4  7]
 [ 9  1  5  3]
 [10  8 11  6]]
[[ 4  5  7  8]
 [10 11  6  2]
 [ 9  1  3  0]]
[[ 5  9  3  0]
 [ 1  8  7  4]
 [ 6 11 10  2]]


In [20]:
print (a)
print (b)
print (c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.52110781 0.91901623 0.07107457 0.72749216]
 [0.27063131 0.89403931 0.52998603 0.90766415]
 [0.32901463 0.14289966 0.49668164 0.02922379]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
d=np.append(a, b)
print(d)


[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.52110781 0.91901623 0.07107457 0.72749216 0.27063131 0.89403931
 0.52998603 0.90766415 0.32901463 0.14289966 0.49668164 0.02922379]


In [38]:
query = '''
SELECT Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species FROM iris'''
sth = cur.execute(query)
daten = np.empty((0,0))
results = sth.fetchall()
for Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species in results:
    daten = np.append(daten, (Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species))


In [39]:
daten.shape

(900,)

In [40]:
900 / 6

150.0

In [42]:
daten=daten.reshape(150,6)

In [46]:
daten.dtype

dtype('<U32')

In [47]:
daten[0,:]

array(['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='<U32')

In [48]:
import pandas as pd


In [53]:
columns = ['Id','SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm','Species']

In [61]:
df = pd.DataFrame(daten, index=daten[:,0], columns=columns)
df.describe(percentiles=[.25, .5, .75])

Id SepalLengthCm SepalWidthCm PetalLengthCm PetalWidthCm      Species
count   150           150          150           150          150          150
unique  150            35           23            43           22            3
top      15             5            3           1.5          0.2  Iris-setosa
freq      1            10           26            14           28           50

In [62]:
df

Id SepalLengthCm SepalWidthCm PetalLengthCm PetalWidthCm         Species
1      1           5.1          3.5           1.4          0.2     Iris-setosa
2      2           4.9            3           1.4          0.2     Iris-setosa
3      3           4.7          3.2           1.3          0.2     Iris-setosa
4      4           4.6          3.1           1.5          0.2     Iris-setosa
5      5             5          3.6           1.4          0.2     Iris-setosa
..   ...           ...          ...           ...          ...             ...
146  146           6.7            3           5.2          2.3  Iris-virginica
147  147           6.3          2.5             5          1.9  Iris-virginica
148  148           6.5            3           5.2            2  Iris-virginica
149  149           6.2          3.4           5.4          2.3  Iris-virginica
150  150           5.9            3           5.1          1.8  Iris-virginica

[150 rows x 6 columns]

In [76]:
import sqlite3
conn = sqlite3.connect("database.sqlite")
df2 = pd.read_sql_query("SELECT Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species FROM iris", con = conn)

In [77]:
df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]